DROP TABLE items_on_order;

  CREATE TABLE SHIPMENTS (
  SHIPMENT_ID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID INT(10) UNSIGNED NOT NULL,
  ITEM_ID INT(10) UNSIGNED NOT NULL,
  SHIPPING_DATE DATE NOT NULL,

  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
  FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID)
)
