CREATE TABLE ADDRESS(

  ADDRESS_ID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  STREET VARCHAR(20)  NOT NULL,
  HOUSENUMBER INT(10) UNSIGNED NOT NULL,
  ZIPCODE INT(10) UNSIGNED NOT NULL,
  CITY VARCHAR(20) NOT NULL
);
