ALTER TABLE CUSTOMERS
    ADD COLUMN EMAIL VARCHAR(20) NOT NULL,
    ADD COLUMN ADDRESS_ID int(10) UNSIGNED NOT NULL,
    ADD COLUMN PHONE VARCHAR(20) NOT NULL,
    ADD FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID);

